name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-chrome:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      #- name: Yarn install cache
      #  uses: c-hive/gha-yarn-cache@v2

      - run: yarn install

      - run: yarn test:ci
        env:
          BROWSER: chrome

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: test-results.json

  #e2e-safari:
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v1
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #    - run: yarn install
  #    - run: |
  #        sudo safaridriver --enable
  #        safaridriver -p 0 &
  #    - run: yarn jest e2e/runWithSelenium.test.ts
  #      env:
  #        BROWSER: safari

  #e2e-firefox:
  #  runs-on: windows-latest
  #  steps:
  #    - uses: actions/checkout@v1
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #    - run: yarn install
  #    - run: yarn jest e2e/runWithSelenium.test.ts
  #      env:
  #        BROWSER: firefox
