name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    
    #container:
    #  image: node:14.18.1
    #  options: --network-alias testHost

    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost

    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-chrome:4.0.0-20211013
        env:
          HUB_HOST: hub
          HUB_PORT: 4444

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
        
      - name: Checkout
        uses: actions/checkout@v1.2.0
        
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install JS dependencies
        run: yarn install
        
      - name: Lint
        run: yarn lint
        
      - name: Test
        run: yarn test
