name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-chrome:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
          
      - name: Yarn install cache
        # You may pin to the exact commit or the version.
        # uses: c-hive/gha-yarn-cache@1188bbd5a9af66e263de707cf9e97b7b7c942969
        uses: c-hive/gha-yarn-cache@v1
          
      - run: yarn install
      
      - run: yarn test
        env:
          BROWSER: chrome

  #e2e-safari:
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v1
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #    - run: yarn install
  #    - run: |
  #        sudo safaridriver --enable
  #        safaridriver -p 0 &
  #    - run: yarn jest e2e/runWithSelenium.test.ts
  #      env:
  #        BROWSER: safari

  #e2e-firefox:
  #  runs-on: windows-latest
  #  steps:
  #    - uses: actions/checkout@v1
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #    - run: yarn install
  #    - run: yarn jest e2e/runWithSelenium.test.ts
  #      env:
  #        BROWSER: firefox
